### ISSUE TITLE
ETA and Open Source?

### ISSUE THREAD

**Issue by Merenon** [ThalesGroup/terraform-provider-ciphertrust#1]
Hi Thales team,
is there any ETA for a stable version 1.x and/or any thoughts about actually open sourcing the provider to allow for community contribution? We'd really like to use it in production.

**Comment by Waqar-Ahmed-ThalesGroup** [comment]
Hi Merenon
We are aiming to open source it by Mid-2023. Current version can be used in production and already being used in production.

**Comment by Merenon** [comment]
Thanks @Waqar-Ahmed-ThalesGroup! Looking forward to it.
