### ISSUE TITLE
Create Key Version using ciphertrust_azure_key

### ISSUE THREAD

**Issue by Mpheus07** [ThalesGroup/terraform-provider-ciphertrust#12]
Is there a way to create a version of a key from existing key using ciphertrust_azure_key or other possible options ?. Based on the below doc, version param is only possible in  read_only mode. 
https://registry.terraform.io/providers/ThalesGroup/ciphertrust/latest/docs/resources/azure_key

**Comment by SarahThompson** [comment]
Hi, yes, to create another Azure key version, create another key resource using the same key name.
