### ISSUE TITLE
provider configuration works only via external file

### ISSUE THREAD

**Issue by TomSp** [ThalesGroup/terraform-provider-ciphertrust#15]
environment
```
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v6.11.2
+ provider registry.terraform.io/hashicorp/random v3.6.3
+ provider registry.terraform.io/thalesgroup/ciphertrust v0.10.6-beta
```

provider "ciphertrust" {
  address      = "https://ciphertrust.dpondemand.io/?tenant=onpier-gmbh-ciphertrustmanager"
  username  = "${var.CIPHERTRUST_USER}"
  password = "${var.CIPHERTRUST_SECRET}"
}

is not working at all 

only via  ~/.ciphertrust/config file

**Comment by martingegenleitner** [comment]
Hi @TomSp ,
you need to follow the provider configuration sample from the docs (https://github.com/ThalesGroup/terraform-provider-ciphertrust?tab=readme-ov-file#for-ciphertrust-data-security-platform-as-a-service-cdspaas). Your configuration misses the parameter "auth_domain" which is mandatory for using the provider with CDSPaaS and holds the tenant id/name (in your case "onpier-gmbh-ciphertrustmanager"). Your provider block should look like this:

```hcl
provider "ciphertrust" {
  address     = "https://ciphertrust.dpondemand.io"
  username    = "LOCAL_CDSP_USER"
  password    = "LOCAL_CDSP_USER_PASSWORD"
  auth_domain = "onpier-gmbh-ciphertrustmanager"
}
```

Please update your provider block and/or configuration file and give us a short feedback if this solves your issue.
Thanks and best regards, Martin

**Comment by TomSp** [comment]
Hello @martingegenleitner ,

yes we tried that, but now again,

leads immediately to


```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: failed to set auth token [NCERRAccountLocked: Account is locked]: User account is temporarily locked. Lockout time remaining '0:01:00'
```

**Comment by TomSp** [comment]
problem fixed due to using a local (non **Data Protection On Demand** - User)

```
provider "ciphertrust" {
  address     = "https://ciphertrust.dpondemand.io"
  username    = "${var.CIPHERTRUST_USER}"
  password    = "${var.CIPHERTRUST_SECRET}"
  auth_domain = "onpier-gmbh-ciphertrustmanager"
}
```
