### ISSUE TITLE
Destroy don't delete public key

### ISSUE THREAD

**Issue by luigi-vezzoso** [ThalesGroup/terraform-provider-ciphertrust#2]
Hi,

I tested TF destroy command over CipherTrust RSA key pairs and I find that public key is not removed by the destroy action.

This generate a series of issue (i.e. I cannot create that key again due existence of the public key) etc.

**Comment by Waqar-Ahmed-ThalesGroup** [comment]
Thanks for feedback. We will look into it right away.

**Comment by Waqar-Ahmed-ThalesGroup** [comment]
It is a valid issue. It being fixed as we speak. Revised TF Provider should be available for download in next couple of days max.

**Comment by luigi-vezzoso** [comment]
I just checked the new version and the issue is solved. Thank You very much for quick response.
